## Packages

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.impute import SimpleImputer

## Membaca Data

In [ ]:
df_train=pd.read_csv("/content/train.csv")
df_test=pd.read_csv("/content/test.csv")
df_train

,id,DC024,DC025,DC205,DC206,DC207,DC208,DC209,DC210,DC211,...,DC237f,DC241,DC242,DC244,DC246,DC252,DC270a,DC109,DC142a,DC201
0,1,11,2,16.0,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,2.0,1,12.0,60.0,Layak Minum
1,2,11,2,31.0,1.0,0.0,1.0,0.0,0.0,1.0,...,0.0,1.0,0.0,1.0,1.0,1.0,2,31.0,70.0,Layak Minum
2,3,11,2,12.0,1.0,0.0,1.0,1.0,1.0,1.0,...,0.0,1.0,0.0,1.0,1.0,0.0,4,11.0,75.0,Layak Minum
3,6,11,2,12.0,1.0,0.0,0.0,0.0,0.0,1.0,...,0.0,2.0,NaN,1.0,0.0,1.0,1,11.0,85.0,Layak Minum
4,7,11,2,12.0,1.0,0.0,1.0,1.0,0.0,0.0,...,0.0,1.0,0.0,0.0,1.0,0.0,2,11.0,65.0,Layak Minum
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35968,47958,94,1,17.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,3.0,NaN,0.0,0.0,0.0,1,21.0,9.0,Layak Minum
35969,47959,94,1,12.0,1.0,0.0,1.0,1.0,0.0,0.0,...,0.0,1.0,1.0,0.0,0.0,0.0,2,11.0,12.0,Layak Minum
35970,47961,94,1,12.0,1.0,0.0,1.0,1.0,0.0,1.0,...,0.0,1.0,1.0,0.0,1.0,1.0,1,11.0,48.0,Layak Minum
35971,47962,94,1,12.0,1.0,0.0,1.0,1.0,0.0,1.0,...,0.0,1.0,1.0,0.0,0.0,0.0,2,11.0,39.0,Layak Minum
35972,47963,94,1,12.0,1.0,0.0,1.0,1.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,0.0,3,11.0,40.0,Layak Minum

In [ ]:
df_test

,id,DC024,DC025,DC205,DC206,DC207,DC208,DC209,DC210,DC211,...,DC237e,DC237f,DC241,DC242,DC244,DC246,DC252,DC270a,DC109,DC142a
0,26718,35,2,17,1,0,1,0,1,1,...,0,0,1,1,1,1,1,3,21,52
1,26802,35,1,12,1,1,1,1,0,1,...,0,0,1,1,0,0,1,2,11,18
2,41302,74,2,12,1,0,1,1,1,1,...,0,0,1,0,0,1,4,5,11,78
3,38698,72,1,12,1,1,0,0,0,0,...,0,0,1,0,1,0,0,1,11,20
4,44257,76,2,12,1,0,1,0,0,1,...,0,0,1,1,1,1,1,3,11,125
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11985,36943,65,2,12,1,0,1,0,0,1,...,0,0,1,0,0,0,0,4,11,70
11986,33415,61,2,12,1,0,1,1,0,1,...,0,1,1,1,1,0,0,4,11,120
11987,41998,74,1,12,1,1,1,1,0,1,...,0,0,1,1,0,0,1,2,11,72
11988,41567,74,2,31,0,0,0,0,0,1,...,0,0,1,0,0,1,1,1,51,9
11989,45296,81,1,12,1,0,1,1,0,0,...,0,0,1,1,0,0,1,2,11,96

# Clearing Data
## Meninjau data

In [ ]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35973 entries, 0 to 35972
Data columns (total 40 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      35973 non-null  int64
 1   DC024   35973 non-null  int64
 2   DC025   35973 non-null  int64
 3   DC205   35962 non-null  float64
 4   DC206   35952 non-null  float64
 5   DC207   35929 non-null  float64
 6   DC208   35960 non-null  float64
 7   DC209   35955 non-null  float64
 8   DC210   35932 non-null  float64
 9   DC211   35949 non-null  float64
 10  DC212   35949 non-null  float64
 11  DC213   35896 non-null  float64
 12  DC214   35964 non-null  float64
 13  DC215   35959 non-null  float64
 14  DC216   35934 non-null  float64
 15  DC217   35973 non-null  int64
 16  DC219   35973 non-null  int64
 17  DC220   35969 non-null  float64
 18  DC226   35967 non-null  float64
 19  DC230a  35962 non-null  float64
 20  DC230b  32964 non-null  float64
 21  DC232   32949 non-null  float64
 22  DC232b  32949 non-null  float64
 23  DC235   25527 non-null  float64
 24  DC237   35952 non-null  float64
 25  DC237a  35936 non-null  float64
 26  DC237b  35936 non-null  float64
 27  DC237c  35936 non-null  float64
 28  DC237d  35936 non-null  float64
 29  DC237e  35936 non-null  float64
 30  DC237f  35936 non-null  float64
 31  DC241   35361 non-null  float64
 32  DC242   30599 non-null  float64
 33  DC244   35969 non-null  float64
 34  DC246   35964 non-null  float64
 35  DC252   35959 non-null  float64
 36  DC270a  35973 non-null  int64
 37  DC109   35962 non-null  float64
 38  DC142a  35921 non-null  float64
 39  DC201   35970 non-null  object
dtypes: float64(33), int64(6), object(1)
memory usage: 11.0+ MB

In [ ]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11990 entries, 0 to 11989
Data columns (total 39 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      11990 non-null  int64
 1   DC024   11990 non-null  int64
 2   DC025   11990 non-null  int64
 3   DC205   11990 non-null  int64
 4   DC206   11990 non-null  int64
 5   DC207   11990 non-null  int64
 6   DC208   11990 non-null  int64
 7   DC209   11990 non-null  int64
 8   DC210   11990 non-null  int64
 9   DC211   11990 non-null  int64
 10  DC212   11990 non-null  int64
 11  DC213   11990 non-null  int64
 12  DC214   11990 non-null  int64
 13  DC215   11990 non-null  int64
 14  DC216   11990 non-null  int64
 15  DC217   11990 non-null  int64
 16  DC219   11990 non-null  int64
 17  DC220   11990 non-null  int64
 18  DC226   11990 non-null  int64
 19  DC230a  11990 non-null  int64
 20  DC230b  11990 non-null  int64
 21  DC232   11990 non-null  int64
 22  DC232b  11990 non-null  int64
 23  DC235   11990 non-null  int64
 24  DC237   11990 non-null  int64
 25  DC237a  11990 non-null  int64
 26  DC237b  11990 non-null  int64
 27  DC237c  11990 non-null  int64
 28  DC237d  11990 non-null  int64
 29  DC237e  11990 non-null  int64
 30  DC237f  11990 non-null  int64
 31  DC241   11990 non-null  int64
 32  DC242   11990 non-null  int64
 33  DC244   11990 non-null  int64
 34  DC246   11990 non-null  int64
 35  DC252   11990 non-null  int64
 36  DC270a  11990 non-null  int64
 37  DC109   11990 non-null  int64
 38  DC142a  11990 non-null  int64
dtypes: int64(39)
memory usage: 3.6 MB

In [ ]:
df_test.shape

(11990, 39)

In [ ]:
df_train.shape

(35973, 40)

In [ ]:
df_train.isnull().sum()

id            0
DC024         0
DC025         0
DC205        11
DC206        21
DC207        44
DC208        13
DC209        18
DC210        41
DC211        24
DC212        24
DC213        77
DC214         9
DC215        14
DC216        39
DC217         0
DC219         0
DC220         4
DC226         6
DC230a       11
DC230b     3009
DC232      3024
DC232b     3024
DC235     10446
DC237        21
DC237a       37
DC237b       37
DC237c       37
DC237d       37
DC237e       37
DC237f       37
DC241       612
DC242      5374
DC244         4
DC246         9
DC252        14
DC270a        0
DC109        11
DC142a       52
DC201         3
dtype: int64

In [ ]:
df_test.isnull().sum()

id        0
DC024     0
DC025     0
DC205     0
DC206     0
DC207     0
DC208     0
DC209     0
DC210     0
DC211     0
DC212     0
DC213     0
DC214     0
DC215     0
DC216     0
DC217     0
DC219     0
DC220     0
DC226     0
DC230a    0
DC230b    0
DC232     0
DC232b    0
DC235     0
DC237     0
DC237a    0
DC237b    0
DC237c    0
DC237d    0
DC237e    0
DC237f    0
DC241     0
DC242     0
DC244     0
DC246     0
DC252     0
DC270a    0
DC109     0
DC142a    0
dtype: int64

In [ ]:
# Mendeteksi duplikat berdasarkan semua kolom
duplicate_rows_train = df_train[df_train.duplicated()]

# Menampilkan baris duplikat
print(duplicate_rows_train)

Empty DataFrame
Columns: [id, DC024, DC025, DC205, DC206, DC207, DC208, DC209, DC210, DC211, DC212, DC213, DC214, DC215, DC216, DC217, DC219, DC220, DC226, DC230a, DC230b, DC232, DC232b, DC235, DC237, DC237a, DC237b, DC237c, DC237d, DC237e, DC237f, DC241, DC242, DC244, DC246, DC252, DC270a, DC109, DC142a, DC201]
Index: []

[0 rows x 40 columns]

In [ ]:
# Mendeteksi duplikat berdasarkan semua kolom
duplicate_rows_test = df_test[df_test.duplicated()]

# Menampilkan baris duplikat
print(duplicate_rows_test)

Empty DataFrame
Columns: [id, DC024, DC025, DC205, DC206, DC207, DC208, DC209, DC210, DC211, DC212, DC213, DC214, DC215, DC216, DC217, DC219, DC220, DC226, DC230a, DC230b, DC232, DC232b, DC235, DC237, DC237a, DC237b, DC237c, DC237d, DC237e, DC237f, DC241, DC242, DC244, DC246, DC252, DC270a, DC109, DC142a]
Index: []

[0 rows x 39 columns]

In [ ]:
df_train.describe()

,id,DC024,DC025,DC205,DC206,DC207,DC208,DC209,DC210,DC211,...,DC237e,DC237f,DC241,DC242,DC244,DC246,DC252,DC270a,DC109,DC142a
count,35973.000000,35973.000000,35973.000000,35962.000000,35952.000000,35929.000000,35960.000000,35955.000000,35932.000000,35949.000000,...,35936.000000,35936.000000,35361.000000,30599.000000,35969.000000,35964.000000,35959.000000,35973.000000,35962.000000,35921.000000
mean,24336.069775,43.229088,1.468601,14.986736,0.960086,0.189234,0.846858,0.569434,0.326700,0.758547,...,0.003451,0.198687,1.167303,0.826922,0.366288,0.379574,1.207014,2.699330,15.498637,82.668216
std,13828.886872,23.585684,0.499020,6.061058,0.195761,0.391700,0.360130,0.495162,0.469013,0.427970,...,0.158921,0.425478,0.457907,0.378320,0.481796,0.485288,1.228101,1.435673,9.598043,91.194377
min,1.000000,11.000000,1.000000,12.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,11.000000,0.000000
25%,12341.000000,31.000000,1.000000,12.000000,1.000000,0.000000,1.000000,0.000000,0.000000,1.000000,...,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,1.000000,11.000000,42.000000
50%,24787.000000,35.000000,1.000000,12.000000,1.000000,0.000000,1.000000,1.000000,0.000000,1.000000,...,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,1.000000,3.000000,11.000000,63.000000
75%,36131.000000,64.000000,2.000000,16.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,...,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,4.000000,12.000000,96.000000
max,47963.000000,94.000000,2.000000,96.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,8.000000,8.000000,6.000000,1.000000,1.000000,1.000000,4.000000,5.000000,96.000000,998.000000

In [ ]:
df_test.describe()

,id,DC024,DC025,DC205,DC206,DC207,DC208,DC209,DC210,DC211,...,DC237e,DC237f,DC241,DC242,DC244,DC246,DC252,DC270a,DC109,DC142a
count,11990.000000,11990.000000,11990.000000,11990.000000,11990.000000,11990.000000,11990.000000,11990.000000,11990.000000,11990.000000,...,11990.000000,11990.000000,11990.0,11990.000000,11990.000000,11990.000000,11990.000000,11990.000000,11990.000000,11990.000000
mean,22919.702085,40.772060,1.545955,14.995163,0.969975,0.194829,0.868474,0.586072,0.353211,0.787740,...,0.002919,0.198916,1.0,0.830442,0.401918,0.421601,1.231193,2.794329,15.399750,83.574145
std,13843.033050,23.383389,0.497904,6.090866,0.170663,0.396086,0.337989,0.492556,0.477987,0.408925,...,0.130091,0.416383,0.0,0.375260,0.490306,0.493836,1.216327,1.408209,9.589858,85.810562
min,4.000000,11.000000,1.000000,12.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,1.0,0.000000,0.000000,0.000000,0.000000,1.000000,11.000000,0.000000
25%,10761.250000,19.000000,1.000000,12.000000,1.000000,0.000000,1.000000,0.000000,0.000000,1.000000,...,0.000000,0.000000,1.0,1.000000,0.000000,0.000000,0.000000,2.000000,11.000000,48.000000
50%,22062.500000,33.000000,2.000000,12.000000,1.000000,0.000000,1.000000,1.000000,0.000000,1.000000,...,0.000000,0.000000,1.0,1.000000,0.000000,0.000000,1.000000,3.000000,11.000000,66.000000
75%,35135.750000,63.000000,2.000000,16.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,...,0.000000,0.000000,1.0,1.000000,1.000000,1.000000,1.000000,4.000000,12.000000,96.000000
max,47960.000000,94.000000,2.000000,96.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,8.000000,8.000000,1.0,1.000000,1.000000,1.000000,4.000000,5.000000,96.000000,998.000000

## Imputing missing value

In [ ]:
df_train = df_train.fillna(df_train.mode().iloc[0])

# Menampilkan DataFrame setelah mengisi nilai null dengan modus
print(df_train)

          id  DC024  DC025  DC205  DC206  DC207  DC208  DC209  DC210  DC211  \
0          1     11      2   16.0    1.0    0.0    1.0    0.0    0.0    0.0
1          2     11      2   31.0    1.0    0.0    1.0    0.0    0.0    1.0
2          3     11      2   12.0    1.0    0.0    1.0    1.0    1.0    1.0
3          6     11      2   12.0    1.0    0.0    0.0    0.0    0.0    1.0
4          7     11      2   12.0    1.0    0.0    1.0    1.0    0.0    0.0
...      ...    ...    ...    ...    ...    ...    ...    ...    ...    ...
35968  47958     94      1   17.0    1.0    0.0    0.0    0.0    0.0    0.0
35969  47959     94      1   12.0    1.0    0.0    1.0    1.0    0.0    0.0
35970  47961     94      1   12.0    1.0    0.0    1.0    1.0    0.0    1.0
35971  47962     94      1   12.0    1.0    0.0    1.0    1.0    0.0    1.0
35972  47963     94      1   12.0    1.0    0.0    1.0    1.0    0.0    1.0

       ...  DC237f  DC241  DC242  DC244  DC246  DC252  DC270a  DC109  DC142a  \
0      ...     0.0    1.0    0.0    0.0    0.0    2.0       1   12.0    60.0
1      ...     0.0    1.0    0.0    1.0    1.0    1.0       2   31.0    70.0
2      ...     0.0    1.0    0.0    1.0    1.0    0.0       4   11.0    75.0
3      ...     0.0    2.0    1.0    1.0    0.0    1.0       1   11.0    85.0
4      ...     0.0    1.0    0.0    0.0    1.0    0.0       2   11.0    65.0
...    ...     ...    ...    ...    ...    ...    ...     ...    ...     ...
35968  ...     0.0    3.0    1.0    0.0    0.0    0.0       1   21.0     9.0
35969  ...     0.0    1.0    1.0    0.0    0.0    0.0       2   11.0    12.0
35970  ...     0.0    1.0    1.0    0.0    1.0    1.0       1   11.0    48.0
35971  ...     0.0    1.0    1.0    0.0    0.0    0.0       2   11.0    39.0
35972  ...     0.0    1.0    0.0    0.0    0.0    0.0       3   11.0    40.0

             DC201
0      Layak Minum
1      Layak Minum
2      Layak Minum
3      Layak Minum
4      Layak Minum
...            ...
35968  Layak Minum
35969  Layak Minum
35970  Layak Minum
35971  Layak Minum
35972  Layak Minum

[35973 rows x 40 columns]

In [ ]:
df_train.isnull().sum()

id        0
DC024     0
DC025     0
DC205     0
DC206     0
DC207     0
DC208     0
DC209     0
DC210     0
DC211     0
DC212     0
DC213     0
DC214     0
DC215     0
DC216     0
DC217     0
DC219     0
DC220     0
DC226     0
DC230a    0
DC230b    0
DC232     0
DC232b    0
DC235     0
DC237     0
DC237a    0
DC237b    0
DC237c    0
DC237d    0
DC237e    0
DC237f    0
DC241     0
DC242     0
DC244     0
DC246     0
DC252     0
DC270a    0
DC109     0
DC142a    0
DC201     0
dtype: int64

# Mengonversi tipe data

In [ ]:
df_train.dtypes

id          int64
DC024       int64
DC025       int64
DC205     float64
DC206     float64
DC207     float64
DC208     float64
DC209     float64
DC210     float64
DC211     float64
DC212     float64
DC213     float64
DC214     float64
DC215     float64
DC216     float64
DC217       int64
DC219       int64
DC220     float64
DC226     float64
DC230a    float64
DC230b    float64
DC232     float64
DC232b    float64
DC235     float64
DC237     float64
DC237a    float64
DC237b    float64
DC237c    float64
DC237d    float64
DC237e    float64
DC237f    float64
DC241     float64
DC242     float64
DC244     float64
DC246     float64
DC252     float64
DC270a      int64
DC109     float64
DC142a    float64
DC201      object
dtype: object

In [ ]:
#menyamakan data menjadi data int
integer_columns = ['DC205', 'DC206', 'DC207', 'DC208', 'DC209', 'DC210', 'DC211', 'DC212', 'DC213', 'DC214',
                   'DC215', 'DC216', 'DC226', 'DC230a', 'DC230b', 'DC232', 'DC232b', 'DC235', 'DC237',
                   'DC237a', 'DC237b', 'DC237c', 'DC237d', 'DC237e', 'DC237f', 'DC241', 'DC242', 'DC244', 'DC246',
                   'DC252', 'DC109']
numeric_columns = ['DC220','DC142a']
# Mengubah tipe data kolom menjadi int64
df_train[integer_columns] = df_train[integer_columns].astype(int)
df_test[numeric_columns]= df_test[numeric_columns].astype(float)
# Memeriksa tipe data setelah perubahan
print(df_train.dtypes)

id          int64
DC024       int64
DC025       int64
DC205       int64
DC206       int64
DC207       int64
DC208       int64
DC209       int64
DC210       int64
DC211       int64
DC212       int64
DC213       int64
DC214       int64
DC215       int64
DC216       int64
DC217       int64
DC219       int64
DC220     float64
DC226       int64
DC230a      int64
DC230b      int64
DC232       int64
DC232b      int64
DC235       int64
DC237       int64
DC237a      int64
DC237b      int64
DC237c      int64
DC237d      int64
DC237e      int64
DC237f      int64
DC241       int64
DC242       int64
DC244       int64
DC246       int64
DC252       int64
DC270a      int64
DC109       int64
DC142a    float64
DC201      object
dtype: object

In [ ]:
df_test.dtypes

id          int64
DC024       int64
DC025       int64
DC205       int64
DC206       int64
DC207       int64
DC208       int64
DC209       int64
DC210       int64
DC211       int64
DC212       int64
DC213       int64
DC214       int64
DC215       int64
DC216       int64
DC217       int64
DC219       int64
DC220     float64
DC226       int64
DC230a      int64
DC230b      int64
DC232       int64
DC232b      int64
DC235       int64
DC237       int64
DC237a      int64
DC237b      int64
DC237c      int64
DC237d      int64
DC237e      int64
DC237f      int64
DC241       int64
DC242       int64
DC244       int64
DC246       int64
DC252       int64
DC270a      int64
DC109       int64
DC142a    float64
dtype: object

In [ ]:
# Mengganti nilai 'Layak Minum' dengan 1 dan 'Tidak Layak Minum' dengan 0
df_train['DC201'] = df_train['DC201'].map({'Layak Minum': 1, 'Tidak Layak Minum': 0})

# Melakukan one-hot encoding pada kolom 'DC201'
encoded_df = pd.get_dummies(df_train, columns=['DC201'], prefix=['DC201'], dummy_na=False)

# Tampilkan hasil encoding
print(encoded_df.head())

   id  DC024  DC025  DC205  DC206  DC207  DC208  DC209  DC210  DC211  ...  \
0   1     11      2     16      1      0      1      0      0      0  ...
1   2     11      2     31      1      0      1      0      0      1  ...
2   3     11      2     12      1      0      1      1      1      1  ...
3   6     11      2     12      1      0      0      0      0      1  ...
4   7     11      2     12      1      0      1      1      0      0  ...

   DC241  DC242  DC244  DC246  DC252  DC270a  DC109  DC142a  DC201_0  DC201_1
0      1      0      0      0      2       1     12    60.0        0        1
1      1      0      1      1      1       2     31    70.0        0        1
2      1      0      1      1      0       4     11    75.0        0        1
3      2      1      1      0      1       1     11    85.0        0        1
4      1      0      0      1      0       2     11    65.0        0        1

[5 rows x 41 columns]

## Pendefinian Skala

In [ ]:
from sklearn.preprocessing import StandardScaler
# Menggunakan Z-score Standardization untuk standarisasi data
scaler = StandardScaler()
standardized_data_train = scaler.fit_transform(df_train)
standardized_data_test = scaler.fit_transform(df_test)

# Membuat DataFrame baru dari data yang sudah di-standarisasi
standardized_df_train = pd.DataFrame(standardized_data_train, columns=df_train.columns)
standardized_df_test = pd.DataFrame(standardized_data_test, columns=df_test.columns)

## Encoding

In [ ]:
from scipy.interpolate import interp1d
# Menghitung nilai Q1 dan Q3
Q1 = df_train['DC220'].quantile(0.25)
Q3 = df_train ['DC220'].quantile(0.75)

# Menghitung rentang IQR
IQR = Q3 - Q1

# Menentukan ambang batas untuk outlier
lower_limit = Q1 - 1.5 * IQR
upper_limit = Q3 + 1.5 * IQR

# Membuat fungsi interpolasi linear
interpolator = interp1d(df_train.index, df_train['DC220'], kind='linear')

# Mengganti outlier dengan nilai yang diinterpolasi
df_train.loc[(df_train['DC220'] < lower_limit) | (df_train['DC220'] > upper_limit), 'DC220'] = interpolator(df_train.index[(df_train['DC220'] < lower_limit) | (df_train['DC220'] > upper_limit)])

In [ ]:
from scipy.interpolate import interp1d
# Menghitung nilai Q1 dan Q3
Q1 = df_train['DC142a'].quantile(0.25)
Q3 = df_train ['DC142a'].quantile(0.75)

# Menghitung rentang IQR
IQR = Q3 - Q1

# Menentukan ambang batas untuk outlier
lower_limit = Q1 - 1.5 * IQR
upper_limit = Q3 + 1.5 * IQR

# Membuat fungsi interpolasi linear
interpolator = interp1d(df_train.index, df_train['DC142a'], kind='linear')

# Mengganti outlier dengan nilai yang diinterpolasi
df_train.loc[(df_train['DC142a'] < lower_limit) | (df_train['DC142a'] > upper_limit), 'DC142a'] = interpolator(df_train.index[(df_train['DC142a'] < lower_limit) | (df_train['DC142a'] > upper_limit)])

In [ ]:
from scipy.interpolate import interp1d
# Menghitung nilai Q1 dan Q3
Q1 = df_test['DC142a'].quantile(0.25)
Q3 = df_test ['DC142a'].quantile(0.75)

# Menghitung rentang IQR
IQR = Q3 - Q1

# Menentukan ambang batas untuk outlier
lower_limit = Q1 - 1.5 * IQR
upper_limit = Q3 + 1.5 * IQR

# Membuat fungsi interpolasi linear
interpolator = interp1d(df_test.index, df_test['DC142a'], kind='linear')

# Mengganti outlier dengan nilai yang diinterpolasi
df_test.loc[(df_test['DC142a'] < lower_limit) | (df_test['DC142a'] > upper_limit), 'DC142a'] = interpolator(df_test.index[(df_test['DC142a'] < lower_limit) | (df_test['DC142a'] > upper_limit)])

In [ ]:
from scipy.interpolate import interp1d
# Menghitung nilai Q1 dan Q3
Q1 = df_test['DC220'].quantile(0.25)
Q3 = df_test ['DC220'].quantile(0.75)

# Menghitung rentang IQR
IQR = Q3 - Q1

# Menentukan ambang batas untuk outlier
lower_limit = Q1 - 1.5 * IQR
upper_limit = Q3 + 1.5 * IQR

# Membuat fungsi interpolasi linear
interpolator = interp1d(df_test.index, df_test['DC220'], kind='linear')

# Mengganti outlier dengan nilai yang diinterpolasi
df_test.loc[(df_test['DC220'] < lower_limit) | (df_test['DC220'] > upper_limit), 'DC220'] = interpolator(df_test.index[(df_test['DC220'] < lower_limit) | (df_test['DC220'] > upper_limit)])

## Modeling

In [ ]:
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import f1_score
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
import xgboost as xgb
import lightgbm as lgb
from sklearn.feature_selection import SelectPercentile, chi2
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import OrdinalEncoder
from sklearn.ensemble import GradientBoostingClassifier

# Pisahkan fitur dan target
X = df_train.drop('DC201', axis=1)
y = df_train['DC201']

# Pisahkan data menjadi data latih dan data uji
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3333, random_state=100)

# List kolom numerik
numeric_cols = ['DC142a', 'DC220']

# List kolom kategorikal
categorical_cols = ['DC206', 'DC207', 'DC208', 'DC209', 'DC210', 'DC211', 'DC212', 'DC213', 'DC214',
                    'DC215', 'DC216', 'DC226', 'DC230a', 'DC230b', 'DC232', 'DC232b', 'DC235', 'DC237',
                    'DC237a', 'DC237b', 'DC237c', 'DC237d', 'DC237e', 'DC237f', 'DC241', 'DC242', 'DC244', 'DC246',
                    'DC252', 'DC109', 'DC217', 'DC219', 'DC270a']

# Preprocessing pipeline untuk fitur numerik
numeric_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())
])

# Preprocessing pipeline untuk fitur kategorikal
categorical_transformer = Pipeline(steps=[
    ('ohe', OneHotEncoder(handle_unknown='ignore')),
    ('selector', SelectPercentile(chi2, percentile=50))
])

# Gabungkan preprocessing pipeline untuk numerik dan kategorikal
preprocessor = ColumnTransformer(transformers=[
    ('cat', categorical_transformer, categorical_cols),
    ('num', numeric_transformer, numeric_cols)
])

# XGBoost
xgboost = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('xgb', xgb.XGBClassifier())
])

# Latih model
xgboost.fit(X_train, y_train)

# Prediksi pada data uji
xgb_pred = xgboost.predict(X_test)

# Prediksi pada df_test
xgb_pred_test = xgboost.predict(df_test)


# Definisikan pipeline dengan preprocessing dan model Random Forest
Random_Forest = Pipeline(steps=[('scaler', StandardScaler()),
                           ('classifier', RandomForestClassifier())])
Random_Forest.fit(X_train,y_train)
rndm=Random_Forest.predict(df_test)

# SVM
svm_model=SVC()
svm=Pipeline([
    ('preprocessor', preprocessor),
    ('svm',svm_model)
])
svm.fit(X_train,y_train)
svmm=svm.predict(df_test)

# LGBM
lgbm = Pipeline([
    ('preprocessor', preprocessor),
    ('lgbm', lgb.LGBMClassifier())
])
lgbm.fit(X_train, y_train)
lgbmm=lgbm.predict(df_test)

#Gradient Boosting
G = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('gb', GradientBoostingClassifier())
])
G.fit(X_train,y_train)
GB=G.predict(df_test)

[LightGBM] [Info] Number of positive: 21614, number of negative: 2369
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.009667 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 472
[LightGBM] [Info] Number of data points in the train set: 23983, number of used features: 75
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.901222 -> initscore=2.210873
[LightGBM] [Info] Start training from score 2.210873

In [ ]:
y_test.shape

(11990,)

## Score

In [ ]:
f1_micro = f1_score(y_test, rndm, average='micro')
print("Skor F1 mikro Random Forest:", f1_micro)

f1_micro = f1_score(y_test, svmm, average='micro')
print("Skor F1 mikro SVM:", f1_micro)

f1_micro = f1_score(y_test, xgb_pred_test, average='micro')
print("Skor F1 mikro XGBoost:", f1_micro)

f1_micro = f1_score(y_test, lgbmm, average='micro')
print("Skor F1 mikro LGBM:", f1_micro)

f1_micro = f1_score(y_test, GB, average='micro')
print("Skor F1 mikro GradientBoosting:", f1_micro)

Skor F1 mikro Random Forest: 0.8750625521267723
Skor F1 mikro SVM: 0.8877397831526271
Skor F1 mikro XGBoost: 0.8658048373644703
Skor F1 mikro LGBM: 0.8721434528773978
Skor F1 mikro GradientBoosting: 0.878231859883236

In [ ]:
# Untuk ngesave
# Buat DataFrame baru dengan kolom 'id' dan 'Predictions'
predictions_df = pd.DataFrame({'id': df_test['id'], 'DC201': lgbmm})

# Ubah nilai prediksi menjadi label yang sesuai
predictions_df['DC201'] = predictions_df['DC201'].map({0: 'tidak layak minum', 1: 'layak minum'})

# Simpan hasil prediksi ke dalam file CSV
predictions_df.to_csv('predictions_lgbm.csv', index=False)

In [ ]:
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from xgboost import XGBClassifier
# Menginisialisasi model yang akan digunakan
model = XGBClassifier()

# Menginisialisasi objek KFold untuk k-fold cross-validation dengan k=5
kfold = KFold(n_splits=5, shuffle=True, random_state=42)

# Melakukan validasi silang
scores = cross_val_score(model, X, y, cv=kfold, scoring='accuracy')

# Menampilkan hasil evaluasi dari setiap fold
print("Hasil evaluasi pada setiap fold:")
for i, score in enumerate(scores):
    print(f"Fold-{i+1}: {score}")

# Menampilkan rata-rata akurasi dan deviasi standar dari semua fold
print("Rata-rata akurasi: ", scores.mean())
print("Deviasi standar: ", scores.std())

Hasil evaluasi pada setiap fold:
Fold-1: 0.9218902015288395
Fold-2: 0.9179986101459346
Fold-3: 0.9145239749826268
Fold-4: 0.9186822351959967
Fold-5: 0.9103419516263553
Rata-rata akurasi:  0.9166873946959505
Deviasi standar:  0.003942408048965219

In [ ]:
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import f1_score
from sklearn.preprocessing import StandardScaler
from xgboost.sklearn import XGBClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import VotingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn import datasets
from sklearn.metrics import accuracy_score
from xgboost import XGBRegressor
#
# Load IRIS dataset
X = df_train.drop('DC201', axis=1)
y = df_train['DC201']
#
# Create training and test data split
#
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3333, random_state=42)

# kolom Numerik
numeric_cols = ['DC142a','DC220']

# Preprocessing pipeline untuk fitur numerik
numeric_transformer = Pipeline(
    steps=[("imputer", SimpleImputer(strategy="median")), ("scaler", StandardScaler())]
)

# List kolom kategorikal
categorical_cols = ['DC205', 'DC206', 'DC207', 'DC208', 'DC209', 'DC210', 'DC211', 'DC212', 'DC213', 'DC214',
                   'DC215', 'DC216', 'DC226', 'DC230a', 'DC230b', 'DC232', 'DC232b', 'DC235', 'DC237',
                   'DC237a', 'DC237b', 'DC237c', 'DC237d', 'DC237e', 'DC237f', 'DC241', 'DC242', 'DC244', 'DC246',
                   'DC252', 'DC109', 'DC024','DC025','DC217','DC219','DC270a']

# Preprocessing pipeline untuk fitur kategorikal

categorical_transformer = Pipeline([
    ('onehot', OneHotEncoder(handle_unknown='ignore'))  # Lakukan one-hot encoding pada fitur kategorikal
])

# Gabungkan preprocessing pipeline untuk numerik dan kategorikal
preprocessor = ColumnTransformer(transformers=[
     ('cat', categorical_transformer, categorical_cols),
     ('num', numeric_transformer, numeric_cols),
])

# Create classifier using logistic regression, randomforest and SVM
#
svm_clf = SVC(probability=True)
clf1 = LogisticRegression(multi_class='multinomial', random_state=1)
clf2 = RandomForestClassifier(n_estimators=50, random_state=1)
clf3 = XGBClassifier(objective="reg:linear", random_state=42)


# Create Voting Classifier
#
voting_clf = VotingClassifier(
    estimators=[('xgb',clf3)], voting='soft')
#
# Fit the model
#
voting_clf.fit(X_train, y_train)
#
# Print the metrics
#
for clf in (clf3, voting_clf):
     clf.fit(X_train, y_train)
     y_pred = clf.predict(df_test)
     print(clf, accuracy_score(y_test,y_pred))

/usr/local/lib/python3.10/dist-packages/xgboost/core.py:160: UserWarning: [14:45:26] WARNING: /workspace/src/objective/regression_obj.cu:209: reg:linear is now deprecated in favor of reg:squarederror.
  warnings.warn(smsg, UserWarning)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=None,
              num_parallel_tree=None, objective='reg:linear', ...) 0.8644703919933278

/usr/local/lib/python3.10/dist-packages/xgboost/core.py:160: UserWarning: [14:45:27] WARNING: /workspace/src/objective/regression_obj.cu:209: reg:linear is now deprecated in favor of reg:squarederror.
  warnings.warn(smsg, UserWarning)

VotingClassifier(estimators=[('xgb',
                              XGBClassifier(base_score=None, booster=None,
                                            callbacks=None,
                                            colsample_bylevel=None,
                                            colsample_bynode=None,
                                            colsample_bytree=None, device=None,
                                            early_stopping_rounds=None,
                                            enable_categorical=False,
                                            eval_metric=None,
                                            feature_types=None, gamma=None,
                                            grow_policy=None,
                                            importance_type=None,
                                            interaction_constraints=None,
                                            learning_rate=None, max_bin=None,
                                            max_cat_threshold=None,
                                            max_cat_to_onehot=None,
                                            max_delta_step=None, max_depth=None,
                                            max_leaves=None,
                                            min_child_weight=None, missing=nan,
                                            monotone_constraints=None,
                                            multi_strategy=None,
                                            n_estimators=None, n_jobs=None,
                                            num_parallel_tree=None,
                                            objective='reg:linear', ...))],
                 voting='soft') 0.8644703919933278

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import StackingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn import datasets
from sklearn.metrics import accuracy_score
#
# Load IRIS dataset
#
iris = datasets.load_iris()
X = df_train.drop('DC201', axis=1)
y = df_train['DC201']
#
# Create training and test data split
#
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)
#
# Create classifier using logistic regression, randomforest and SVM
#
svm_clf = SVC()
#
# Create Voting Classifier
#
stacking_clf = StackingClassifier(estimators=svm_clf)

# Fit the model
#
stacking_clf.fit(X_train, y_train)
#
# Print the metrics
#
for clf in (svm_clf, stacking_clf):
     clf.fit(X_train, y_train)
     y_pred = clf.predict(X_test)
     print(clf, accuracy_score(y_test,y_pred))
     f1_micro = f1_score(y_test, y_pred, average='micro')
print("Skor F1 mikro SVM:", f1_micro)

InvalidParameterError: ignored

In [ ]:
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import f1_score
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
import xgboost as xgb
import lightgbm as lgb
from sklearn.neural_network import MLPClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier

# Pisahkan fitur dan target
X = df_train.drop('DC201', axis=1)
y = df_train['DC201']

# Pisahkan data menjadi data latih dan data uji
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3333, random_state=100)

# List kolom kategorikal
categorical_cols = ['DC205', 'DC206', 'DC207', 'DC208', 'DC209', 'DC210', 'DC211', 'DC212', 'DC213', 'DC214',
                   'DC215', 'DC216', 'DC220', 'DC226', 'DC230a', 'DC230b', 'DC232', 'DC232b', 'DC235', 'DC237',
                   'DC237a', 'DC237b', 'DC237c', 'DC237d', 'DC237e', 'DC237f', 'DC241', 'DC242', 'DC244', 'DC246',
                   'DC252', 'DC109', 'DC142a','DC024','DC025','DC217','DC219','DC270a']

# Preprocessing pipeline untuk fitur kategorikal

categorical_transformer = Pipeline([
    ('onehot', OneHotEncoder(handle_unknown='ignore'))  # Lakukan one-hot encoding pada fitur kategorikal
])
# Gabungkan preprocessing pipeline untuk numerik dan kategorikal
preprocessor = ColumnTransformer(transformers=[
     ('cat', categorical_transformer, categorical_cols),
     ('num', numeric_transformer, numeric_cols),
])
# Definisikan pipeline dengan preprocessing dan model Random Forest
Random_Forest = Pipeline(steps=[('scaler', StandardScaler()),
                           ('classifier', RandomForestClassifier())])
Random_Forest.fit(X_train,y_train)
rndm=Random_Forest.predict(df_test)

# SVM
svm_model=SVC()
svm=Pipeline([
    ('svm',svm_model)
])
svm.fit(X_train,y_train)
svmm=svm.predict(df_test)
# XGBoost
xgboost = Pipeline([
    ('xgb', xgb.XGBClassifier())
])
xgboost.fit(X_train, y_train)
xgbost=xgboost.predict(df_test)

# LGBM
lgbm = Pipeline([
    ('lgbm', lgb.LGBMClassifier())
])
lgbm.fit(X_train, y_train)
lgbmm=lgbm.predict(df_test)

# KNN
knn = Pipeline([
    ('knn', KNeighborsClassifier())
])
knn.fit(X_train,y_train)
knnn=knn.predict(df_test)

# Decision tree
decisiontree = Pipeline([
    ('dt', DecisionTreeClassifier())
])
decisiontree.fit(X_train,y_train)
dectree=decisiontree.predict(df_test)

# NN
NN = Pipeline([
    ('nn', MLPClassifier())
])
NN.fit(X_train, y_train)
nn=NN.predict(df_test)

[LightGBM] [Info] Number of positive: 21614, number of negative: 2369
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.009148 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 765
[LightGBM] [Info] Number of data points in the train set: 23983, number of used features: 38
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.901222 -> initscore=2.210873
[LightGBM] [Info] Start training from score 2.210873